<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Kernel\Storage\MediaCollection;
use App\Kernel\Storage\MediaStore;
use Symfony\Component\HttpFoundation\Response;

/**
 * Serves a center's PUBLIC media (logos, catalog and site imagery) from the
 * center's own host.
 *
 * The tenancy filesystem bootstrapper roots the `public` disk at
 * `tenants/{key}/app/public`, so the global `/storage` symlink can never reach
 * a center's files. This route runs inside the resolved center, reads only
 * from that center's disk, and only from the public collections: a private
 * collection has no public URL by construction (docs/09-STORAGE.md §7).
 *
 * Paths are generated by MediaStore (collection/uuid.ext), so anything else —
 * traversal, another collection, an unexpected extension — is simply not
 * found. Responses are immutable (names are never reused), sniff-proof and
 * sandboxed, so even a mislabelled file cannot execute.
 */
final class CenterMediaController extends Controller
{
    /** Extension → the only content type it is ever served as. */
    private const TYPES = [
        'jpg' => 'image/jpeg',
        'jpeg' => 'image/jpeg',
        'png' => 'image/png',
        'webp' => 'image/webp',
        'ico' => 'image/x-icon',
        'mp4' => 'video/mp4',
        'webm' => 'video/webm',
    ];

    public const PATTERN = '(branding|catalog)/[A-Fa-f0-9-]{36}\.(jpg|jpeg|png|webp|ico|mp4|webm)';

    public function __invoke(string $center, string $path, MediaStore $store): Response
    {
        if (preg_match('#^'.self::PATTERN.'$#', $path, $match) !== 1) {
            abort(404);
        }

        $collection = MediaCollection::from($match[1]);
        if (! $store->exists($collection, $path)) {
            abort(404);
        }

        // The store answers byte ranges where its driver can (Safari/WebKit
        // need them to play a video) — this controller never learns which.
        return $store->response($collection, $path, [
            'Content-Type' => self::TYPES[mb_strtolower($match[2])],
            'Cache-Control' => 'public, max-age=31536000, immutable',
            'X-Content-Type-Options' => 'nosniff',
            'Content-Security-Policy' => "default-src 'none'; sandbox",
            'Cross-Origin-Resource-Policy' => 'same-site',
        ]);
    }
}
