<?php

declare(strict_types=1);

namespace App\Kernel\Tenancy\Exceptions;

use InvalidArgumentException;

/**
 * Guards every code path that interpolates a database name into SQL.
 *
 * Database identifiers cannot be bound as parameters, so the only defence is
 * refusing to accept anything that was not generated by our own policy
 * (docs/02-TENANCY.md §4.1).
 */
final class InvalidTenantDatabaseName extends InvalidArgumentException
{
    public static function for(string $name): self
    {
        return new self(
            "Refusing to operate on database [{$name}]: it does not match the Meta Style "
            .'tenant database naming policy. Database names are generated from the internal '
            .'tenant sequence and are never derived from user input.'
        );
    }
}
